fixed xtensor version
otherwise one would get

/opt/conda/conda-bld/nifty_1529067953236/work/src/python/lib/graph/opt/lifted_multicut/pixel_wise_lifted_multicut.cxx:95:9:   required from 'void nifty::graph::opt::lifted_multicut::exportPixelWiseLmcStuffT(pybind11::module&) [with long unsigned int DIM = 3ul]'
/opt/conda/conda-bld/nifty_1529067953236/work/src/python/lib/graph/opt/lifted_multicut/pixel_wise_lifted_multicut.cxx:151:57:   required from here
/opt/conda/conda-bld/nifty_1529067953236/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/include/xtensor/xview.hpp:1015:59: error: invalid use of void expression